coverage:
  status:
    patch:
      default:
        enabled: true
        target: auto
        threshold: 5%
        if_ci_failed: error
        if_not_found: error
        if_unhealthy: error
        if_no_uploads: error
        informational: false
    project:
      target: 80%
      threshold: 5%
      scanner:
        paths:
          - src/scanner*
          - tests/lex*
        flags:
          - scanner
        target: 80%
        threshold: 15%
      stack:
        paths:
          - tests/stack*
          - src/stack*
        flags:
          - stack
        target: 80%
        threshold: 5%