coverage:
  status:
    project:
      default:
        enabled: true
        target: 90%
        threshold: 10%
        if_ci_failed: error
        if_not_found: failure
        if_unhealthy: error
        if_no_uploads: error
        informational: false
      scanner:
        paths:
          - src/scanner*
          - tests/lex*
        flags:
          - scanner
        target: 80%
        threshold: 15%
      stack:
        paths:
          - tests/stack*
          - src/stack*
        flags:
          - stack
        target: 80%
        threshold: 5%
    patch:
      default:
        enabled: true
        target: 90%
        threshold: 5%
        if_ci_failed: error
        if_not_found: error
        if_unhealthy: error
        if_no_uploads: error
        informational: false


flags:
    scanner:
        paths:
        - src/scanner*
        - tests/lex*
        carryforward: true
    stack:
        paths:
        - tests/stack*
        - src/stack*