coverage:
  range: 60..80
  status:
    project: off
    patch: off
    changes: off

comment:
  graph: sunburst
  layout: header, diff, changes, sunburst, flags, files, footer
  behavior: default
  require_changes: false

flags:
  scanner:
    paths:
      - src/scanner*
      - tests/lex*
    target: 80%
    threshold: 5%
    carryforward: true
  stack:
    paths:
      - tests/stack*
      - src/stack*
    target: 80%
    threshold: 5%
    informational: true
    carryforward: true